--
--Copyright suprtypo@pm.me.
--LICENSED ONLY FOR THE PURPOSE OF INTEGRATING WITH THE KASPA CRYPTOCURRENCY NETWORK.
--

CREATE TABLE addresses_known
(
    address VARCHAR PRIMARY KEY,
    name    VARCHAR NOT NULL
);
